import type { CategoryInfo, DeliveryZone } from "@/types";

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "pizza",
    nameAr: "البيتزا",
    nameEn: "Pizza",
    icon: "🍕",
    image: "/images/categories/pizza.jpg",
    color: "#D62828",
  },
  {
    id: "stromboli",
    nameAr: "الاسترومبولي",
    nameEn: "Stromboli",
    icon: "🌯",
    image: "/images/categories/stromboli.jpg",
    color: "#C2410C",
  },
  {
    id: "burger",
    nameAr: "البرجر",
    nameEn: "Burger",
    icon: "🍔",
    image: "/images/categories/burger.jpg",
    color: "#B45309",
  },
  {
    id: "souri",
    nameAr: "السوري",
    nameEn: "Souri",
    icon: "🥙",
    image: "/images/categories/souri.jpg",
    color: "#065F46",
  },
  {
    id: "crepes-chicken",
    nameAr: "كريبات الفراخ",
    nameEn: "Chicken Crepes",
    icon: "🥞",
    image: "/images/categories/crepes-chicken.jpg",
    color: "#7C3AED",
  },
  {
    id: "crepes-meat",
    nameAr: "كريبات اللحوم",
    nameEn: "Meat Crepes",
    icon: "🥩",
    image: "/images/categories/crepes-meat.jpg",
    color: "#9F1239",
  },
  {
    id: "crepes-fries",
    nameAr: "كريبات البطاطس",
    nameEn: "Fries Crepes",
    icon: "🍟",
    image: "/images/categories/crepes-fries.jpg",
    color: "#CA8A04",
  },
  {
    id: "crepes-mix",
    nameAr: "كريبات المكس",
    nameEn: "Mix Crepes",
    icon: "🎉",
    image: "/images/categories/crepes-mix.jpg",
    color: "#0369A1",
  },
  {
    id: "twister-specials",
    nameAr: "اختراعات تويستر",
    nameEn: "Twister Specials",
    icon: "🌟",
    image: "/images/categories/twister-specials.jpg",
    color: "#D62828",
  },
  {
    id: "additions",
    nameAr: "الإضافات",
    nameEn: "Additions",
    icon: "➕",
    image: "/images/categories/additions.jpg",
    color: "#374151",
  },
];

export const DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: "rawda",
    nameAr: "الروضة",
    nameEn: "Al-Rawda",
    deliveryFee: 10,
    minOrder: 60,
    estimatedTime: "25-35 دقيقة",
  },
  {
    id: "shahid-fakri",
    nameAr: "الشهيد فكري",
    nameEn: "Al-Shahid Fakri",
    deliveryFee: 10,
    minOrder: 60,
    estimatedTime: "25-35 دقيقة",
  },
  {
    id: "abu-mashhour",
    nameAr: "أبو مشهور",
    nameEn: "Abu Mashhour",
    deliveryFee: 10,
    minOrder: 60,
    estimatedTime: "25-40 دقيقة",
  },
  {
    id: "barka-al-saba",
    nameAr: "بركة السبع",
    nameEn: "Barka Al-Saba",
    deliveryFee: 15,
    minOrder: 60,
    estimatedTime: "30-45 دقيقة",
  },
];
